### ISSUE TITLE
Machine learning samples duplication

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#18373]
Machine learning samples exist in both repos, dotnet/docs and dotnet/samples.

https://github.com/dotnet/docs/tree/master/samples/snippets/machine-learning/
https://github.com/dotnet/samples/tree/master/machine-learning/tutorials/

They should be kept in one place and deleted from the other.

**Comment by BillWagner** [comment]
/cc @Thraka @luisquintanilla 

Andy, what did we decide here?

**Comment by Thraka** [comment]
If I remember correctly, the samples repo is linked to from the documentation. The copy in this repo is used for snippets. To keep them separated via context, you shouldn't tell users to browse the snippet version, they should browse the samples version. This is why the samples copy remains.

**Comment by Youssef1313** [comment]
@Thraka wouldn't that make maintenance harder?
They can get out-of-sync easily.

**Comment by luisquintanilla** [comment]
So for the time being, we can link wherever it makes sense. I believe some work was done to point our docs to snippets in docs repo. Over time, we'll migrate to the dotnet/machinelearning-samples repo since we'd want users to be able to access the completed version of the app, but for the time being, as long as users can get a full version of the app, we're flexible.

**Comment by Thraka** [comment]
@Youssef1313 Yes it will. Someone will have to know that there is a sample to update. But keeping the cleanest code possible for a customer to download and use is the best choice. When I download a sample, I don't want to delete tons of `<Snippet192391>` comments. Some methods can have multiple snippet tags too; it makes the code very ugly.

**Comment by Youssef1313** [comment]
@Thraka Just an idea, can't you have a bot that is configurable to keep the code in-sync?

For example:

**sync_bot.yml**:

```yml
samples:
  - with_snippet: "Path for sample 1"
    without_snippet: "Another path for sample 1"
  - with_snippet: "Path for sample 2"
    without_snippet: "Another path for sample 2"
  - with_snippet: "Path for sample 3"
    without_snippet: "Another path for sample 3"
```

Where the "with_snippet" path is the file that contains the `<snippet>` tags and that is the file being maintained, and "without_snippet" path is a file without snippet tags that **only** that bot should touch it. Whenever a change is made to "with_snippet" sample, the bot detects that and update the other one.

That way, customer will have access to non-polluted sample, and the code is more maintainable, and the process is less error-prone.
