### ISSUE TITLE
Completed tutorial but nothing worked (web apps)

### ISSUE THREAD

**Issue by vslzl** [dotnet/docs#27667]
The steps have been followed in MacOS with VS for Mac but in the end, app doesn't work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83e95a3f-447b-8ca0-beb5-f0363896fe29
* Version Independent ID: b24e3ee5-404c-98a2-042e-6ac2d363b842
* Content: [Get started with Dapr](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/getting-started)
* Content Source: [docs/architecture/dapr-for-net-developers/getting-started.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/getting-started.md)
* Product: **dotnet-architecture**
* GitHub Login: @amolenk
* Microsoft Alias: **nanil**

**Comment by amolenk** [comment]
Hi @vslzl

That chapter explains getting started using VS Code and Visual Studio 2022 (for Windows). We haven't tested yet with Visual Studio for Mac. Can you elaborate on what doesn't work?

Thanks!

**Comment by vslzl** [comment]
I've fixed the issue it was related to the `dotnet dev-certs https --trust` configuration on macos with docker.

Working docker-compose.override variant is:
and you can't debug, only run.

```
version: '3.4'

services:
  myfrontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password_here
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5100:80"
      - "5101:443"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
```

[ref: Generate self-signed certificates with the .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/self-signed-certificates-guide#with-dotnet-dev-certs)  

First of all, this is not your fault. The VS for Mac app is a big drawback for developers on macos. Since the F5 run experience configuration for docker-compose makes understanding of these concepts very hard. If you can't debug whats going on it's hard to develop.
