### ISSUE TITLE
Can not run the K8S pods following the 2 yaml file

### ISSUE THREAD

**Issue by dengyakui** [dotnet/docs#29161]
[Enter feedback here]

I copy & paste the 2 deploy YAML file content, and change the image name to my own acr's image. but can not start pod normally.
Looks like the pod is always restarting.
----------
[WebApi.zip](https://github.com/dotnet/docs/files/8549134/WebApi.zip)

I uploaded the sample source code, hope anyone can help me.

![image](https://user-images.githubusercontent.com/3945919/164959995-517870be-af5c-4844-860f-9326197e8303.png)

![image](https://user-images.githubusercontent.com/3945919/164959834-bd166e73-2a7f-4557-bcd1-91b3c67fee90.png)
---
##### webapi deploy yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: weather-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapi
  template:
    metadata:
      labels:
        app: weather-forecast
        service: webapi
    spec:
      containers:
        - name: webapi
          image: quintos.azurecr.io/webapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: webapi
  labels:
    app: weather-forecast
    service: webapi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: webapi
```

##### webapp deploy yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: weather-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: weather-forecast
        service: webapp
    spec:
      containers:
        - name: webapp
          image: quintos.azurecr.io/webapp:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: WebApiBaseAddress
              value: http://webapi
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: weather-forecast
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: webapp
```

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95aa8619-2154-00fb-5994-09b7a9673e03
* Version Independent ID: 182cacc8-12d1-70ac-6005-71d4f6f420d5
* Content: [Build ASP.NET Core applications deployed as Linux containers into AKS/Kubernetes clusters](https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes)
* Content Source: [docs/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md](https://github.com/dotnet/docs/blob/main/docs/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md)
* Product: **dotnet-architecture**
* Technology: **containerized-lifecycle**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**
