### ISSUE TITLE
GitHub actions do support stages, just not named the same

### ISSUE THREAD

**Issue by Lance-Simeon** [dotnet/docs#31227]
This document states that GitHub actions don't support stages, but multi-dimension jobs are stages with a different name: 
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-using-a-multi-dimension-matrix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea049336-6c09-1791-a102-cede5fa3ebff
* Version Independent ID: 36ffb095-5a05-8516-ab25-1120b3c22979
* Content: [DevOps with .NET and GitHub Actions - Compare GitHub Actions with Azure Pipelines](https://docs.microsoft.com/en-us/dotnet/architecture/devops-for-aspnet-developers/actions-vs-pipelines)
* Content Source: [docs/architecture/devops-for-aspnet-developers/actions-vs-pipelines.md](https://github.com/dotnet/docs/blob/main/docs/architecture/devops-for-aspnet-developers/actions-vs-pipelines.md)
* Product: **dotnet-architecture**
* GitHub Login: @colindembovsky
* Microsoft Alias: **nanil**

**Comment by colindembovsky** [comment]
@Lance-Simeon These are _not_ the same things. "Stages" in Azure DevOps are really _groups of jobs_ - but the jobs don't have to have the same steps. The `matrix` allows you to execute _exactly_ the same steps with slightly different parameters. The `matrix` is really a way to _repeat_ a job with slightly different parameters. 

With Stages in Pipelines, I may want to have _different_ jobs for different stages - for example, if I have jobs called `build`, `deploy` and `loadTest`, I may want a workflow file that looks something like this:

```yml
stages:
- stage: Build
  jobs:
  - job: build

- stage: DeployToDev
  dependsOn: Build
  jobs:
  - job: deploy

- stage: DeployToLab
  dependsOn: Build
  jobs:
  - job: Deploy
  - job: loadTest

- stage: DeployToProd
  dependsOn:
  - DeployToDev
  - DeployToLab
  jobs:
  - job: Deploy

```

However, if I am building a nodeJS app for different versions of nodeJS, I can use a `matrix` to specify the steps a single time and then "multiply" those out to each version of nodeJS.

**Comment by Lance-Simeon** [comment]
So the matrix link was incorrect, but you can do this GitHub actions:


```
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Set Up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
  Deploy:
      if: github.event_name != 'schedule'
      needs: Build
      name: Deploy to GitHub Packages
      environment: GitHub Packages
      runs-on: windows-latest
      steps:
        - name: Set Up .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.x'
  
        - name: Download Artifact from Previous Job
          uses: actions/download-artifact@v2
          with:
            name: ${{ env.ArtifactName }}
```
